version: 1
auto-merge-settings:
    merge_level: "minor"
    merge_strategy: "squash"
    skip_ci: false
    delete_branch: true
    commit_title: Auto-merge dependabot PR
    commit_message: Auto-merge dependabot PR by @dependabot-auto-merge
    skip_check_runs: false
