name: deploy

on: workflow_dispatch
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      -
        name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      -
        name: deploy to docker
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.ZEROTIER_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            /usr/local/bin/docker stop nyabot
            /usr/local/bin/docker rm nyabot
            /usr/local/bin/docker image rm whydesd/nyabot:dev
            /usr/local/bin/docker pull whydesd/nyabot:dev
            /usr/local/bin/docker create -p 5600:3000 -e GOCQ_HTTP_URL="http://10.0.0.2:5700" --name nyabot
            /usr/local/bin/docker start nyabot
